[package]
name = "Terse"
version = "0.1.0"
edition = "2024"

# https://www.rustadventure.dev/building-a-digital-garden-cli/structopt-0.3/changing-the-name-of-the-default-cargo-binary
[[bin]]
name = "trs"
path = "./src/main.rs"

[dependencies]
bytesize = "2.3.1"
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.30.0"
reqwest = { version = "0.13.3", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
indoc = "2"
url = {version = "2.5.8", features = ["serde"]}
anyhow = "1.0.102"
directories = "6.0.0"
thiserror = "2.0.18"
text_io = "0.1.13"
derive-new = "0.7.0"
colored = "3.1.1"
time-format = "1.2.2"
capitalize = "0.3.4"
once_cell = "1.21.4"
parking_lot = "0.12.5"

# https://stackoverflow.com/questions/29008127/why-are-rust-executables-so-huge
# maybe optimize a bit for speed also?
# also remember the defaults:
# https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles
[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
